<?php

return [
    'about' => [
        'fr' => trim((string) env('SITE_SLUG_ABOUT', 'a-propos'), '/'),
        'en' => 'about',
        'es' => 'acerca-de',
        'pt' => 'sobre',
        'it' => 'chi-siamo',
        'de' => 'uber-uns',
    ],
    'services' => [
        'fr' => trim((string) env('SITE_SLUG_SERVICES', 'services'), '/'),
        'en' => 'services',
        'es' => 'servicios',
        'pt' => 'servicos',
        'it' => 'servizi',
        'de' => 'dienstleistungen',
    ],
    'contact' => [
        'fr' => trim((string) env('SITE_SLUG_CONTACT', 'contact'), '/'),
        'en' => 'contact',
        'es' => 'contacto',
        'pt' => 'contato',
        'it' => 'contatto',
        'de' => 'kontakt',
    ],
    'account' => [
        'fr' => trim((string) env('SITE_SLUG_ACCOUNT', 'compte'), '/'),
        'en' => 'account',
        'es' => 'cuenta',
        'pt' => 'conta',
        'it' => 'account',
        'de' => 'konto',
    ],
    'funding_request' => [
        'fr' => trim((string) env('SITE_SLUG_FUNDING_REQUEST', 'demande-financement'), '/'),
        'en' => 'funding-request',
        'es' => 'solicitud-financiacion',
        'pt' => 'pedido-financiamento',
        'it' => 'richiesta-finanziamento',
        'de' => 'finanzierungsantrag',
    ],
    'funding_request_confirmation' => [
        'fr' => trim((string) env('SITE_SLUG_FUNDING_CONFIRMATION', 'confirmation'), '/'),
        'en' => 'confirmation',
        'es' => 'confirmacion',
        'pt' => 'confirmacao',
        'it' => 'conferma',
        'de' => 'bestaetigung',
    ],
    'dossier_tracking' => [
        'fr' => trim((string) (env('SITE_SLUG_DOSSIER_TRACKING') ?: 'suivi-dossier'), '/'),
        'en' => 'application-tracking',
        'es' => 'seguimiento-expediente',
        'pt' => 'acompanhamento-processo',
        'it' => 'tracciamento-pratica',
        'de' => 'antragsverfolgung',
    ],
    'legal' => [
        'fr' => trim((string) env('SITE_SLUG_LEGAL', 'mentions-legales'), '/'),
        'en' => 'legal-notice',
        'es' => 'aviso-legal',
        'pt' => 'informacoes-legais',
        'it' => 'note-legali',
        'de' => 'rechtliche-hinweise',
    ],
    'privacy' => [
        'fr' => trim((string) env('SITE_SLUG_PRIVACY', 'politique-de-confidentialite'), '/'),
        'en' => 'privacy-policy',
        'es' => 'politica-de-privacidad',
        'pt' => 'politica-de-privacidade',
        'it' => 'politica-sulla-riservatezza',
        'de' => 'datenschutzrichtlinie',
    ],
];
